apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.7.3
          args:
            - "agent"
            - "-server"
            - "-client"
            - "0.0.0.0"
            - "-ui"
            - "-bootstrap-expect=1"
            - "-data-dir=/consul/data"
            - "-datacenter=blr"
          ports:
            - containerPort: 8500
            - containerPort: 8600
          volumeMounts:
            - mountPath: /consul/data
              name: consul-data
      volumes:
        - name: consul-data
          persistentVolumeClaim:
            claimName: consul-config

---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
    - port: 8500
      targetPort: 8500
  selector:
    app: consul


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 