apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-one-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-one-db
  template:
    metadata:
      labels:
        app: service-one-db
    spec:
      containers:
      - name: mongo
        image: mongo:3.7
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: service-one-db
spec:
  ports:
  - port: 27017
    targetPort: 27017  
  selector:
    app: service-one-db
  type: ClusterIP 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
