apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-two-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-two-db
  template:
    metadata:
      labels:
        app: service-two-db
    spec:
      containers:
      - name: mysql
        image: mysql/mysql-server:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root123"
        - name: MYSQL_DATABASE
          value: "service-two"
        - name: MYSQL_USER
          value: "service-two"
        - name: MYSQL_PASSWORD
          value: "service-two"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: service-two-db
spec:
  ports:
  - port: 3306
  selector:
    app: service-two-db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
