apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-application
  template:
    metadata:
      labels:
        app: web-application
    spec:
      containers:
      - name: web-application
        image: ulsyou/web-application:latest
        ports:
        - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: web-application
spec:
  type: NodePort
  ports:
  - port: 4200
  selector:
    app: web-application
